<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Ganesh" failures="0" tests="2" name="com.vtiger.organizationTest.CreateOrganizationTest" time="1.025" errors="1" timestamp="23 May 2022 13:02:02 GMT" skipped="1">
  <testcase classname="com.vtiger.organizationTest.CreateOrganizationTest" name="createOrganizationTest" time="0.000">
    <skipped/>
  </testcase> <!-- createOrganizationTest -->
  <testcase classname="com.vtiger.organizationTest.CreateOrganizationTest" name="beforeclassTest" time="1.025">
    <error message="Cannot invoke &quot;com.sdet34l1.genericlibrary.WebDriverUse.initializeActions(org.openqa.selenium.WebDriver)&quot; because &quot;this.webDriverUse&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.sdet34l1.genericlibrary.WebDriverUse.initializeActions(org.openqa.selenium.WebDriver)" because "this.webDriverUse" is null
at com.sdet34l1.genericlibrary.BaseClass.beforeclassTest(BaseClass.java:105)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </error>
  </testcase> <!-- beforeclassTest -->
</testsuite> <!-- com.vtiger.organizationTest.CreateOrganizationTest -->
